(define (problem down-ER2068-Tsilosani)
  (:domain blocks-world)
  (:objects a b c d e - block)
  (:init
    (on b a)
    (on c b)
    (on e d)
    (onfloor a)
    (onfloor d)
    (clear c)
    (clear e)
    (handempty)
  )
  (:goal
    (forall (?x - block)
      (onfloor ?x)
    )
  )
)
