(define (problem tower-ER2068-Tsilosani)
  (:domain blocks-world)
  (:objects a b c d e - block)
  (:init
    (onfloor a)
    (onfloor b)
    (onfloor c)
    (onfloor d)
    (onfloor e)
    (clear a)
    (clear b)
    (clear c)
    (clear d)
    (clear e)
    (handempty)
  )
  (:goal
    (exists (?base - block)
      (and
        (onfloor ?base)
        (forall (?x - block)
          (or
            (= ?x ?base)
            (exists (?y - block)
              (on ?x ?y)
            )
          )
        )
      )
    )
  )
)
